Expose C++ code generation via rosidl generate CLI
ros2/rosidl pull request #570
Opened 2021-02-09 16:09 UTC by hidmic

Built on top of #567. Connected to #565.

2021-03-09 17:32 UTC, ahcorde requested changes
Same comments as this other PR and fix the conflics

2021-03-10 07:17 UTC, ahcorde requested changes

2021-03-10 07:17 UTC, ahcorde commented on rosidl_generator_cpp/package.xml
> +  <exec_depend>rosidl_cli</exec_depend>
include `ament_index_python` as a `<exec_depend>`

2021-03-10 13:47 UTC, hidmic commented
Running CI up to `rosidl_generator_cpp`:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13862)](http://ci.ros2.org/job/ci_linux/13862/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8717)](http://ci.ros2.org/job/ci_linux-aarch64/8717/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11571)](http://ci.ros2.org/job/ci_osx/11571/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13951)](http://ci.ros2.org/job/ci_windows/13951/)

2021-03-10 16:05 UTC, ahcorde approved these changes

2021-03-10 18:22 UTC, merged