Add option to rosidl_generate_interfaces to skip dependency export.
ros2/rosidl pull request #708
Opened 2022-09-27 20:05 UTC by clalancette

When a dependency is declared in rosidl_generate_interfaces(), ament_export_dependencies() for that dependency is automatically called.  That is the correct default behavior, but it isn't always the behavior that is wanted.  In particular, if a package has messages that are only used for tests, we don't want to export those dependencies downstream.  Add an option to skip dependency export for rosidl_generate_interfaces.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This came out of https://github.com/ros-tooling/libstatistics_collector/pull/54 , and `libstatistics_collector` will be the first user of it.

2022-09-28 18:38 UTC, clalancette commented
CI for this is over in https://github.com/ros-tooling/libstatistics_collector/pull/145#issuecomment-1261028442

2022-09-30 23:19 UTC, sloretz requested changes
I think this should use the existing `SKIP_INSTALL` variable. It's already used to skip exporting targets, libraries, and dependencies in downstream generators.

https://github.com/ros2/rosidl_typesupport/blob/9fe935124b2a4f5c662f241850c03223855e8fc6/rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake#L140-L161

2022-10-01 18:08 UTC, clalancette commented
That's fair.  Made that change in 9013e83f176a4d7e66e288e0d8aa102597139417; please take another look.

2022-10-04 16:43 UTC, sloretz approved these changes

2022-10-04 18:04 UTC, clalancette commented
Latest CI for this is over in https://github.com/ros-tooling/libstatistics_collector/pull/145#issuecomment-1265545356 (and it is green).  So going ahead and merging this; thanks for the review!

2022-10-04 18:06 UTC, merged